name: Workflow for the RPG CI/CD

on:
  push:
    branches:
      - dev

jobs:
  test_and_push:
    name: Test and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Run tests
        run: python src/rpg_test.py

      - name: Stash changes
        run: git stash --include-untracked

      - name: Fetch updates from remote
        run: git fetch origin

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev branch into main
        run: git merge --ff-only origin/dev

      - name: Push to main branch
        run: git push origin main

      - name: Apply stashed changes
        run: git stash pop

      - name: Handle test failures
        if: failure()
        run: |
          current_date=$(date +%Y%m%d)
          counter_file="failure_branch_counter.txt"
          if [ -f "$counter_file" ]; then
            counter=$(cat "$counter_file")
            counter=$((counter + 1))
          else
            counter=1
          fi
          echo "$counter" > "$counter_file"
          unique_branch_suffix="${current_date}_$counter"
          git checkout -b failure/$unique_branch_suffix
          git push origin failure/$unique_branch_suffix
          
          git checkout dev
          git reset --soft HEAD~1
          git push origin dev --force
